### ISSUE TITLE
AES-256 CTR DRBG: No vetted conditioning component

### ISSUE THREAD

**Issue by afazio2** [usnistgov/ESV-Server#36] opened 2023-06-14 09:37 UTC
My noise source has an AES-256 CTR DRBG conditioning component.
Following IG D.K bullet (7) Note 1. "A CAVP-validated SP 800-90A DRBG may be considered a vetted conditioning component."

I register:

```
      {
        "sequencePosition":2,
        "description":"ctrDRBG",
        "vetted":true,
        "validationNumber":"A3814",
        "minNin":320,
        "minHin":297.0,
        "nw":256,
        "nOut":256,
        "hOut":256.0
      }
```

The server returns the following error:

```
  {
    "conditioningComponents": {
      "elementList": [
        {
          "location": "SequencePosition: 2",
          "messageList": [
            "DescriptionError: description: ctrDRBG does not exist in the VettedConditioningComponentAttributes table.",
            "DependencyFailed: nw cannot be validated because its dependent property Description Result Code is Fail.",
            "DependencyFailed: nOut cannot be validated because its dependent property Description Result Code is Fail.",
            "DependencyFailed: hOut cannot be validated because its dependent property NOut Result Code is Fail."
          ]
        }
      ]
    }
  }
```

**Comment by celic** [comment] 2023-06-15 19:56
This is being added in a release we are preparing for Demo this week and Prod the following week.

**Comment by celic** [comment] 2023-06-22 20:18
Duplicate of #33, but this is going out to Demo today or tomorrow as part of RELEASE/v1.4

**Closed by celic** 2023-06-22 20:18 UTC
